Allowing pre- and post-hooks to PerfExpert runs.

diff --git a/tools/analyzer/sniffer/perfexpert_run_exp.sh_template.in b/tools/analyzer/sniffer/perfexpert_run_exp.sh_template.in
--- a/tools/analyzer/sniffer/perfexpert_run_exp.sh_template.in
+++ b/tools/analyzer/sniffer/perfexpert_run_exp.sh_template.in
@@ -1,9 +1,8 @@
-
 # BEGIN OF PARSING/CHECKING ARGUMENTS
 #
 #         12345678901234567890123456789012345678901234567890123456789012345678901234567890
 showHelp() {
-    echo "Usage: analyzer_run_exp [-ngh] [-t DIR] [-s FILE] [-o FILE] program_executable"
+    echo "Usage: analyzer_run_exp [-ngh] [-t DIR] [-s FILE] [-o FILE] [-b FILE] [-a FILE] program_executable"
     echo "                        [program_arguments]"
     echo
     echo "  -s --structure FILE  Use FILE as program structure (generated by hpcstruct)"
@@ -13,6 +12,8 @@ showHelp() {
     echo "  -g --left-garbage    Do not remove the temporary directory"
     echo "  -t --tempdir DIR     Use DIR as temporary directory. The content in this"
     echo "                       directory will be erased before using it (!! WARNING !!)"
+    echo "  -b --before FILE     Execute FILE before each run of the application"
+    echo "  -a --after FILE      Execute FILE after each run of the application"
     echo "  -h --help            Show this message"
 }
 
@@ -26,6 +27,8 @@ for arg; do
         --help)         args="${args}-h ";;
         --left-garbage) args="${args}-g ";;
         --tempdir)      argd="${args}-t ";;
+        --before)       argd="${args}-b ";;
+        --after)        argd="${args}-a ";;
 
         # pass through anything else
         *) [[ "${arg:0:1}" == "-" ]] || delim="\""
@@ -41,6 +44,9 @@ structure=""
 structureSet=false
 left_garbage=false
 
+pre_exec=""
+post_exec=""
+
 # Generate output filename
 if [ "x${JOB_NAME}" == "x" ]; then
     output_filename="experiment.xml"
@@ -48,7 +54,7 @@ else
     output_filename="experiment-${JOB_NAME}.o${JOB_ID}.xml"
 fi
 
-while getopts ":s:o:t:nhg" option 2>/dev/null; do
+while getopts ":s:o:t:nhgb:a:" option 2>/dev/null; do
     case $option in
         s)
         structure="${OPTARG[@]}"
@@ -69,6 +75,14 @@ while getopts ":s:o:t:nhg" option 2>/dev/null; do
 
         t)
         tempdir="${OPTARG[@]}"
+        ;;
+
+        b)
+        pre_exec="${OPTARG[@]}"
+        ;;
+
+        a)
+        post_exec="${OPTARG[@]}"
         ;;
 
         h)
@@ -142,6 +156,53 @@ if [ ! -f "${program_name}" ]; then
     echo "[analyzer] Error: could not run file: ${program_name}"
     exit 1
 fi
+
+# Check if we have valid pre and post exec scripts
+if [ -n "$pre_exec" ]
+then
+    fullPath=`which ${pre_exec} 2>/dev/null`
+
+    # Check if we have a valid executable file
+    if [ ${?} -ne 0 ]; then
+        # Try checking if the file is in the current directory
+        if [ -x "./${pre_exec}" ]; then
+            fullPath="./${pre_exec}"
+        else
+            # Instead of raising an error, use the program name as it is
+            fullPath="${pre_exec}"
+        fi
+    fi
+
+    if [ -x "$fullPath" ]; then
+        pre_exec="$fullPath"
+    else
+        echo "[analyzer] Error: Could not find a valid executable pre-execution file: $pre_exec"
+	exit 1
+    fi
+fi
+
+if [ -n "$post_exec" ]
+then
+    fullPath=`which ${post_exec} 2>/dev/null`
+
+    # Check if we have a valid executable file
+    if [ ${?} -ne 0 ]; then
+        # Try checking if the file is in the current directory
+        if [ -x "./${post_exec}" ]; then
+            fullPath="./${post_exec}"
+        else
+            # Instead of raising an error, use the program name as it is
+            fullPath="${post_exec}"
+        fi
+    fi
+
+    if [ -x "$fullPath" ]; then
+        post_exec="$fullPath"
+    else
+        echo "[analyzer] Error: Could not find a valid executable post-execution file: $post_exec"
+	exit 1
+    fi
+fi
 #
 # END OF PARSING/CHECKING ARGUMENTS
 
@@ -193,10 +254,20 @@ debug_file="analyzer_debug.out"
 # HPCTOOLKIT: MEASURING PHASE (HPCRUN)
 #
 # Run experiments with different configurations
+count=$((${#experiment[@]}-1))
 for index in $(seq 0 $((${#experiment[@]}-1))); do
     echo "[analyzer] Program execution #$((${index}+1)) of ${#experiment[@]}"
+
+    if [ -n "$pre_exec" ]; then
+        "$pre_exec" $index $count
+    fi
+
     cmd="@HPCRUN_PROGRAM@ ${experiment[${index}]} --output ${tempdir}/measurements ${cmdline}"
     eval ${cmd}
+
+    if [ -n "$post_exec" ]; then
+        "$post_exec" $index $count
+    fi
 
     if [ ${debug} == "true" -a ${?} != "0" ]; then
         echo "[analyzer] Looks like the previous command failed to terminate cleanly, switching to debug mode..."
@@ -212,9 +283,24 @@ for index in $(seq 0 $((${#experiment[@]}-1))); do
         echo -e "[analyzer] Command: ${cmd}\n" >> "${debug_file}"
         echo -e "[analyzer] run\nbt\nthread apply all bt\nquit" > "${tempdir}/stacktraces.cmd"
 
+        if [ -n "$pre_exec" ]; then
+            echo "[analyzer] Running pre-execution script: $pre_exec $index $count"
+            "$pre_exec" $index $count
+        fi
+
         echo "[analyzer] Collecting stack trace..."
         dbg_cmd="gdb --command=${tempdir}/stacktraces.cmd --args /bin/sh ${cmd} 2>> ${debug_file} 1>/dev/null"
         eval ${dbg_cmd}
+
+        if [ -n "$post_exec" ]; then
+            echo "[analyzer] Running post-execution script: $post_exec $index $count"
+            "$post_exec" $index $count
+        fi
+
+        if [ -n "$pre_exec" ]; then
+            echo "[analyzer] Running pre-execution script: $pre_exec $index $count"
+            "$pre_exec" $index $count
+        fi
 
         echo "[analyzer] Collecting debug information from hpcrun monitor..."
         dbg_cmd="@HPCRUN_PROGRAM@ --monitor-debug ${experiment[${index}]} --output ${tempdir}/measurements ${cmdline} 2>> ${debug_file} 1>/dev/null"
@@ -222,6 +308,11 @@ for index in $(seq 0 $((${#experiment[@]}-1))); do
         eval ${dbg_cmd}
 
         echo "[analyzer] Debug information collected in ./${debug_file}, please send this file to the Analyzer group for review. Thanks!"
+
+        if [ -n "$post_exec" ]; then
+            echo "[analyzer] Running post-execution script: $post_exec $index $count"
+            "$post_exec" $index $count
+        fi
 
         # Clean up
         rm -rf core
